### ISSUE TITLE
No connection possible / "DoWrite data = System.Byte[]"

### ISSUE THREAD

**Issue by StefanKoenigMUC** [Quobject/SocketIoClientDotNet#153]
Hi all,

i tried to connect to the socket.io api from iextrading (https://ws-api.iextrading.com/1.0/tops), but was not able to connect to the API by using the SocketIoClientDotNet client (Connection to a socket.io server on localhost is also working fine). 

Only output i get from the application (and not invoked by myself) is shown below:
`DoWrite data = System.Byte[]
DoWrite data = System.Byte[]
DoWrite data = System.Byte[]
DoWrite data = System.Byte[]`

This output is result of the code below, in accordance to the api documentation:
`            var uri = new Uri("https://ws-api.iextrading.com/1.0/tops");
            //uri = new Uri("http://localhost:3000/");
            socket = IO.Socket(uri);
            socket.On("connect", () =>
            {
                Console.WriteLine("connected");
            });`

I was successfully able to establish a connection and subscribe to some channels using the socket.io tester application - therefore it seems to me, that this is not a problem with the API of iextrading.

Dou you have any advice how to proceed with this problem?

thanks in advance,
Stefan

**Comment by juanluelguerre** [comment]
Hi StefanKoenigMUC,

Can you provide us more detail of your sample?. Mainly, when DoWrie data = Sysem.Byte[]… appear means, you are trying to send message in a wrong way.

Here, on my fork, you can find completed sample on detail: https://github.com/juanluelguerre/SocketIoClientDotNet/blob/master/README.md

Regards
Juanlu

**Comment by StefanKoenigMUC** [comment]
here are full code examples for c# and node.js (node.js is working!) - or what kind of additional details is serviceable?

NodeJS Example:

`const socket = require('socket.io-client')('https://ws-api.iextrading.com/1.0/tops')

// Listen to the channel's messages
socket.on('message', message => console.log(message))

// Connect to the channel
socket.on('connect', () => {

  // Subscribe to topics (i.e. appl,fb,aig+)
  socket.emit('subscribe', 'snap,fb,aig+')

  // Unsubscribe from topics (i.e. aig+)
  socket.emit('unsubscribe', 'aig+')
})

// Disconnect from the channel
socket.on('disconnect', () => console.log('Disconnected.'))`

results in: 
`C:\nodejs\socket-io-example>node index.js
{"symbol":"SNAP","sector":"softwareservices","securityType":"commonstock","bidPrice":11.0300,"bidSize":900,"askPrice":11.0400,"askSize":700,"lastUpdated":1526068780047,"lastSalePrice":11.0350,"lastSaleSize":100,"lastSaleTime":1526068779223,"volume":801953,"marketPercent":0.05238,"seq":11695}
{"symbol":"FB","sector":"softwareservices","securityType":"commonstock","bidPrice":186.9800,"bidSize":100,"askPrice":187.0100,"askSize":100,"lastUpdated":1526068780505,"lastSalePrice":187.0000,"lastSaleSize":100,"lastSaleTime":1526068778098,"volume":1149681,"marketPercent":0.06676,"seq":59677}
{"symbol":"AIG+","sector":"n/a","securityType":"warrant","bidPrice":0.0000,"bidSize":0,"askPrice":0.0000,"askSize":0,"lastUpdated":1526068700779,"lastSalePrice":14.2400,"lastSaleSize":300,"lastSaleTime":1526068699610,"volume":36424,"marketPercent":0.23266,"seq":687}`


C#:

           ` Socket socket;
            var uri = new Uri("https://ws-api.iextrading.com/1.0/tops");
            socket = IO.Socket(uri);
            socket.On("connect", () =>
            {
                Console.WriteLine("connected!!!");
            });
            socket.On("message", (msg) => { Console.WriteLine(msg); });
            socket.On("connect", () =>
            {

                // Subscribe to topics (i.e. appl,fb,aig+)
                socket.Emit("subscribe", "snap,fb,aig+");

                // Unsubscribe from topics (i.e. aig+)
                socket.Emit("unsubscribe", "aig+");
            });`

Results in:

`DoWrite data = System.Byte[]`

**Comment by w1ndr1d3r** [comment]
I bumped into same issue (consuming IEX data over socket.io). 

We had our .NET app working fine for almost a month and then it suddenly stopped receiving data. The _Connect_ event stopped firing. No errors/exceptions and nothing interesting in output. 

We were using v1.0.5. Upgraded to 1.0.6 today - no change.

Then I built the DLL from recent source codes and app **started receiving data**.

I believe there must have been some changes on server side (IEX) since client app was working fine and then stopped being able to connect for no reason (no changes on our end). 

Anyway, looks like recent code updates should fix the problem.

**Comment by StefanKoenigMUC** [comment]
Seems to be a working solution, built it from the repository some minutes ago, now it seems to be working. 

But there are still some 
`DoWrite data = System.Byte[]` 
lines printed to the console.

I'm going to write IEX, maybe they can provide some further information about this problem.

**Comment by KaviAbhishekVenkat** [comment]
With the latest commit I tried to connect with my IEX server over socket but still getting the same issue of 
`DoWrite data = System.Byte[] DoWrite data = System.Byte[] DoWrite data = System.Byte[] DoWrite data = System.Byte[]`
